-- Copy and Paste this into your Supabase SQL Editor to initialize your tables!

-- Create Doctors Table
CREATE TABLE public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT,
  role TEXT,
  experience TEXT,
  location TEXT,
  fee TEXT,
  satisfaction TEXT,
  stories TEXT,
  avatar TEXT,
  availability TEXT[], 
  gender TEXT
);

-- Insert Mock Doctor Data
INSERT INTO public.doctors (name, specialty, role, experience, location, fee, satisfaction, stories, avatar, availability, gender) VALUES
('Dr. Aryan Sharma', 'Cardiologist • MBBS, MD (Cardiology)', 'Senior Cardiologist & Heart Surgeon', '15 years experience overall', 'Fortis Memorial, Gurugram', '₹800', '98%', '450+', 'https://i.pravatar.cc/150?img=11', ARRAY['Available Today', 'Available Tomorrow', 'Next 3 Days'], 'Male'),
('Dr. Meera Iyer', 'Pediatrician • MBBS, DCH', 'Senior Pediatrician', '10 years experience overall', 'Max Super Speciality, Saket', '₹600', '96%', '210+', 'https://i.pravatar.cc/150?img=5', ARRAY['Available Tomorrow', 'Next 3 Days'], 'Female'),
('Dr. Vikram Reddy', 'Dermatologist • MD (Derm), DNB', 'Consultant Dermatologist', '22 years experience overall', 'Apollo Hospitals, Sarita Vihar', '₹1200', '99%', '890+', 'https://i.pravatar.cc/150?img=8', ARRAY['Available Today', 'Next 3 Days'], 'Male'),
('Dr. Sana Sheikh', 'Gynecologist • MBBS, MS (OBG)', 'Lead Gynecologist', '12 years experience overall', 'Cloudnine Hospital, Noida', '₹900', '95%', '340+', 'https://i.pravatar.cc/150?img=9', ARRAY['Available Today', 'Available Tomorrow'], 'Female'),
('Dr. Arjun Patel', 'Neurologist • MBBS, DM (Neurology)', 'Consultant Neurologist', '18 years experience overall', 'Medanta, Gurugram', '₹1500', '97%', '560+', 'https://i.pravatar.cc/150?img=12', ARRAY['Next 3 Days'], 'Male'),
('Dr. Kavita Singh', 'Dentist • BDS, MDS', 'Senior Dental Surgeon', '8 years experience overall', 'Clove Dental, South Ex', '₹400', '94%', '180+', 'https://i.pravatar.cc/150?img=10', ARRAY['Available Today', 'Available Tomorrow', 'Next 3 Days'], 'Female'),
('Dr. Rahul Verma', 'General Physician • MBBS, MD', 'Family Medicine Specialist', '25 years experience overall', 'BLK Super Speciality, Delhi', '₹700', '98%', '920+', 'https://i.pravatar.cc/150?img=14', ARRAY['Available Today', 'Next 3 Days'], 'Male');


-- Create Bookings Table
CREATE TABLE public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT REFERENCES public.doctors(id),
  doctor_name TEXT,
  day INT,
  slot TEXT,
  fee TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) but set it to allow anonymous public access for testing (Remove in production!)
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to doctors" ON public.doctors FOR SELECT USING (true);
CREATE POLICY "Allow public insert to bookings" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read to bookings" ON public.bookings FOR SELECT USING (true);

-- Create Medications Table
CREATE TABLE public.medications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dosage TEXT,
  indication TEXT,
  schedule TEXT,
  remaining TEXT,
  type TEXT,
  status TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for medications
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;

-- Allow public access for testing purposes
CREATE POLICY "Allow public read access to medications" ON public.medications FOR SELECT USING (true);
CREATE POLICY "Allow public insert to medications" ON public.medications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to medications" ON public.medications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to medications" ON public.medications FOR DELETE USING (true);

-- Insert Mock Medication Data
INSERT INTO public.medications (name, dosage, indication, schedule, remaining, type, status, icon) VALUES
('Lisinopril', '10mg', 'Hypertension Management', '8:00 AM Daily', '12 / 30', 'pills', 'Refill Now', 'pill'),
('Metformin', '500mg', 'Type 2 Diabetes Control', 'With Breakfast', '5 / 60', 'pills', 'Refill Urgent', 'pill_off'),
('Vitamin D3', '2000IU', 'Immune Support', '1x Weekly (Sun)', '24 / 24', 'caps', 'Refill Not Ready', 'medication_liquid');
